export const Footerli = [
  {
    list: [
      { heading: "Development Services" },
      { li: "Product Design" },
      { li: "MVP Development" },
      { li: "Continuous Prodcts Development" },
      { li: "DevOps Solutions" },
      { li: "Architecture Consulting" },
      { li: "Mobile Application Development" },
      { li: "Enterprise Web Development" },
      { li: "Voice/Alexa App Development" },
      { li: "loT App Development" },
      { li: "BlockChain App Development" },
      { li: "Al BOT Development" },
      { li: "Mobile App Maaintenance" },
    ],
  },
  {
    list: [
      { heading: "Dedicated Resources" },
      { li: "Hire Swift Developer" },
      { li: "Hire ios/iphone Developer" },
      { li: "Hire Fluter Developer" },
      { li: "Hire React Native Developer" },
      { li: "Hire Android Developer" },
      { li: "Hire Angular Developer" },
      { li: "Hire Node.js Developer" },
      { li: "Hire Vue. js Developer" },
      { li: "Hire Raect js Developer" },
      { li: "Hire Laravel Developer" },
      { li: "Hire Golrang Developer" },
      { li: "Hire Full Stack Developer" },
    ],
  },
  {
    list: [
      { heading: "Industry Solutions" },
      { li: "Fitness Secter" },
      { li: "Wellness Area" },
      { li: "Health Service" },
      { li: "Food & Hyperiocal" },
      { li: "elearning Solutions" },
      { li: "Social & Dating" },
      { li: "Travel & Holidays" },
      { li: "Fintech Solutions" },
      { li: "Ecomm & Marketplace" },
      { li: "Jobs & Employment" },
      { li: "Real Estate Sector" },
      { li: "Software Maintenance Support" },
    ],
  },
  {
    list: [
      { heading: "Enterprise" },
      { li: "On Demand App Decelopment" },
      { li: "Field Sales & Service" },
      { li: "Decument Management" },
      { li: "Hippa Compliances" },
      { li: "Software Testing Service" },
      { li: "Logistic & Distribution" },
      { li: "Enterprise App Integration" },
      { li: "Cloud Infrastructure" },
      { li: "Business Intelligence" },
      { li: "Enterpise Mobility" },
      { li: "Staff Augmentation Srvices" },
      { li: "Inspection" },
    ],
  },
];
