export const TechnologyStackmockup = [
  {
    heading: "Front-end frameworks and libraries",
    btn: [
      { language: "React" },
      { language: "Angular" },
      { language: "Vue.js" },
      { language: "jQuery" },
    ],
    cardclass: "technologys  col-lg-6 ",
    rows: "row",
    language: "techlang d-flex flex-wrap",
    lang: "textreact1 mx-1",
  },
  {
    heading: "Development tools and libraries",
    btn: [
      { language: "Git" },
      { language: "Docker" },
      { language: "Jenkins" },
      { language: "Apache Maven" },
      { language: "Gulp" },
      { language: "Grunt" },
      { language: "NPM" },
    ],
    cardclass: "technologys   col-lg-6 ",
    rows: "row",
    language: "techlang d-flex flex-wrap",
    lang: "textreact1 mx-1",
  },
  {
    heading: "Back-end frameworks",
    btn: [
      { language: "Spring" },
      { language: "Express" },
      { language: "Laravel" },
      { language: " Ruby on Rails " },
    ],
    cardclass: "technologys   col-lg-3 ",
    rows: "row",
    language: "techlang d-flex flex-wrap",
    lang: "textreact1 mx-1",
  },
  {
    heading: "MEAN stack",
    btn: [
      { language: "MongoDB" },
      { language: "Express" },
      { language: "AngularJS" },
      { language: "Node.js " },
    ],
    cardclass: "technologys   col-lg-3 ",
    rows: "row",
    language: "techlang d-flex flex-wrap",
    lang: "textreact1 mx-1",
  },
  {
    heading: "LAMP stack",
    btn: [
      { language: "Linux" },
      { language: "Apache" },
      { language: "MySQL" },
      { language: "PHP" },
    ],
    cardclass: "technologys   col-lg-3 ",
    rows: "row",
    language: "techlang d-flex flex-wrap",
    lang: "textreact1 mx-1",
  },
  {
    heading: "Ruby on Rails",
    btn: [
      { language: "Ruby" },
      { language: "Rails" },
      { language: "PostgreSQL" },
    ],
    cardclass: "technologys   col-lg-3 ",
    rows: "row",
    language: "techlang d-flex flex-wrap",
    lang: "textreact1 mx-1",
  },
  {
    heading: "Front-end frameworks and libraries",
    btn: [
      { language: "React" },
      { language: "Angular" },
      { language: "Vue.js" },
      { language: "jQuery" },
    ],
    cardclass: "technologys   col-lg-6",
    rows: "row",
    language: "techlang d-flex flex-wrap",
    lang: "textreact1 mx-1",
  },
  {
    heading: "Django stack",
    btn: [
      { language: "Python" },
      { language: "Django" },
      { language: "PostgreSQL" },
    ],
    cardclass: "technologys   col-lg-6",
    rows: "row",
    language: "techlang d-flex flex-wrap",
    lang: "textreact1 mx-1",
  },
];
